server:
  port: 8888
spring:
  profiles:
    active: native

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoint:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh