### 여기는 이제 CI만 그리고 메인 서버에 깃 pull 할 때만 사용

name: CI for main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Integration:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: JDK install
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Caching Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradle
        run: chmod +x ./gradlew

      - name: create build file
        run: ./gradlew clean build -i --no-daemon

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/libs/*.jar